<?php
    if(isset($page)) {
        $action = 'edit';
    } else {
        $action = 'add';
    }
?>

<form action="<?= url_for(option('backend_url'), $action); ?>" method="post" id="page_form" name="page_form">
    <div class="row">
        <label for="title">Title</label>
        <input type="text" id="title" name="title" value="<?= isset($page) ? $page['title'] : '' ?>" />
    </div>
    <div class="row">
        <label for="slug">Slug</label>
        <small>A slug is a simple version of the title.</small>
        <input type="text" id="slug" name="slug" value="<?= isset($page) ? $page['slug'] : '' ?>" />
    </div>
    <div class="row">
        <label for="body">Body text</label>
        <textarea id="body" name="body"><?= isset($page) ? $page['body'] : '' ?></textarea>
    </div>
    <div class="row">
        <label for="template">Page template</label>
        <select id="template" disabled="disabled">
            <option value="">default</option>    
        </select>
    </div>
    <div class="row">
        <label for="layout">Layout</label>
        <select id="layout" name="layout"<?= (count($layouts) === 0) ? ' disabled="disabled"' : '' ?>>
            <option value="">none</option>
            <?php if(isset($layouts)) : foreach($layouts as $name => $file) : ?>
            <option value="<?= $file ?>"><?= $name ?></option>
            <?php endforeach; endif; ?>
        </select>
    </div>
    
    <div class="row">
        <label for="homepage" class="checkbox">Is homepage?</label>
        <input type="checkbox" id="homepage" name="homepage" />
    </div>
    
    <div class="row row-buttons">
        <input type="submit" id="save" name="save" value="Save" /> or <a href="<?= url_for(option('backend_url'), 'dashboard'); ?>">cancel</a>
        <input type="hidden" id="uid" name="uid" value="<?= isset($page) ? $page['uid'] : '' ?>" />
    </div>
</form>
